// index.js
// 获取应用实例
const app = getApp()
var choseid;
Page({
  data: {
    leftmenulist:[],
    choseid:1,
    rightcontent:[]
  },

  onLoad:function(option){
    let leftmenulist = [
      {
        id:1,
        classname:"类别1",
        children:[
          {
            forumtitle:"论坛标题1",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题2",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题3",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题4",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题5",
            forumcreator:"论坛作者",
            forumdate:"日期"
          }
        ]
      },
      {
        id:2,
        classname:"类别2",
        children:[
          {
            forumtitle:"论坛标题6",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题7",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题8",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题9",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题10",
            forumcreator:"论坛作者",
            forumdate:"日期"
          }
        ]
      },
      {
        id:3,
        classname:"类别3",
        children:[
          {
            forumtitle:"论坛标题",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题",
            forumcreator:"论坛作者",
            forumdate:"日期"
          }
        ]
      },
      {
        id:4,
        classname:"类别4",
        children:[
          {
            forumtitle:"论坛标题",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题",
            forumcreator:"论坛作者",
            forumdate:"日期"
          }
        ]
      },
      {
        id:5,
        classname:"类别5",
        children:[
          {
            forumtitle:"论坛标题",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题",
            forumcreator:"论坛作者",
            forumdate:"日期"
          }
        ]
      },
      {
        id:6,
        classname:"类别6",
        children:[
          {
            forumtitle:"论坛标题",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题",
            forumcreator:"论坛作者",
            forumdate:"日期"
          }
        ]
      },
      {
        id:7,
        classname:"类别7",
        children:[
          {
            forumtitle:"论坛标题",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题",
            forumcreator:"论坛作者",
            forumdate:"日期"
          },
          {
            forumtitle:"论坛标题",
            forumcreator:"论坛作者",
            forumdate:"日期"
          }
        ]
      },
    ]
    let rightcontent = leftmenulist[0].children;
    this.setData({
      leftmenulist,
      rightcontent
    })
  },

  selectclass(e){
    const  index   = e.currentTarget.dataset.index;
    console.log(this.data.leftmenulist[index].children);
    let rightcontent = this.data.leftmenulist[index].children;
    const choseid = index + 1;
    console.log(choseid);
    this.setData({
      rightcontent,
      choseid
    })
  }
})


